export const QUALIFIED_TEAMS_2026 = [
  "México",
  "Sudáfrica",
  "Corea del Sur",
  "Chequia",
  "Canadá",
  "Bosnia y Herzegovina",
  "Catar",
  "Suiza",
  "Brasil",
  "Marruecos",
  "Haití",
  "Escocia",
  "Estados Unidos",
  "Paraguay",
  "Australia",
  "Turquía",
  "Alemania",
  "Curazao",
  "Costa de Marfil",
  "Ecuador",
  "Países Bajos",
  "Japón",
  "Suecia",
  "Túnez",
  "Bélgica",
  "Egipto",
  "Irán",
  "Nueva Zelanda",
  "España",
  "Cabo Verde",
  "Arabia Saudí",
  "Uruguay",
  "Francia",
  "Senegal",
  "Irak",
  "Noruega",
  "Argentina",
  "Argelia",
  "Austria",
  "Jordania",
  "Portugal",
  "RD Congo",
  "Uzbekistán",
  "Colombia",
  "Inglaterra",
  "Croacia",
  "Ghana",
  "Panamá",
] as const;

export const QUALIFIED_TEAM_SET_2026 = new Set<string>(QUALIFIED_TEAMS_2026);
