const FLAG_EMOJI_BY_KEY: Record<string, string> = {
  mexico: "🇲🇽",
  sudafrica: "🇿🇦",
  corea_del_sur: "🇰🇷",
  corea: "🇰🇷",
  chequia: "🇨🇿",
  republica_checa: "🇨🇿",
  canada: "🇨🇦",
  bosnia_y_herzegovina: "🇧🇦",
  catar: "🇶🇦",
  qatar: "🇶🇦",
  suiza: "🇨🇭",
  brasil: "🇧🇷",
  marruecos: "🇲🇦",
  haiti: "🇭🇹",
  escocia: "🏴",
  estados_unidos: "🇺🇸",
  eeuu: "🇺🇸",
  usa: "🇺🇸",
  paraguay: "🇵🇾",
  australia: "🇦🇺",
  turquia: "🇹🇷",
  alemania: "🇩🇪",
  curazao: "🇨🇼",
  costa_de_marfil: "🇨🇮",
  costa_marfil: "🇨🇮",
  ecuador: "🇪🇨",
  paises_bajos: "🇳🇱",
  holanda: "🇳🇱",
  japon: "🇯🇵",
  suecia: "🇸🇪",
  tunez: "🇹🇳",
  belgica: "🇧🇪",
  egipto: "🇪🇬",
  iran: "🇮🇷",
  nueva_zelanda: "🇳🇿",
  espana: "🇪🇸",
  cabo_verde: "🇨🇻",
  arabia_saudi: "🇸🇦",
  arabia_saudita: "🇸🇦",
  uruguay: "🇺🇾",
  francia: "🇫🇷",
  senegal: "🇸🇳",
  irak: "🇮🇶",
  iraq: "🇮🇶",
  noruega: "🇳🇴",
  argentina: "🇦🇷",
  argelia: "🇩🇿",
  austria: "🇦🇹",
  jordania: "🇯🇴",
  portugal: "🇵🇹",
  rd_congo: "🇨🇩",
  rd_del_congo: "🇨🇩",
  uzbekistan: "🇺🇿",
  colombia: "🇨🇴",
  inglaterra: "🏴",
  croacia: "🇭🇷",
  ghana: "🇬🇭",
  panama: "🇵🇦",
  italia: "🇮🇹",
  jamaica: "🇯🇲",
  bolivia: "🇧🇴",
  dinamarca: "🇩🇰",
  emiratos_arabes_unidos: "🇦🇪",
  eslovaquia: "🇸🇰",
  gales: "🏴",
  kosovo: "🇽🇰",
  macedonia_del_norte: "🇲🇰",
  nueva_caledonia: "🇳🇨",
  polonia: "🇵🇱",
  rumania: "🇷🇴",
  surinam: "🇸🇷",
  ucrania: "🇺🇦",
  irlanda: "🇮🇪",
  irlanda_del_norte: "🇬🇧",
};

const FILE_KEY_OVERRIDES: Record<string, string> = {
  estados_unidos: "usa",
  eeuu: "usa",
  usa: "usa",
  paises_bajos: "holanda",
  holanda: "holanda",
  corea_del_sur: "corea",
  corea: "corea",
  costa_de_marfil: "costa-marfil",
  costa_marfil: "costa-marfil",
  catar: "qatar",
  qatar: "qatar",
  irak: "iraq",
  iraq: "iraq",
  chequia: "republica-checa",
  republica_checa: "republica-checa",
  rd_congo: "rd-congo",
  rd_del_congo: "rd-congo",
  arabia_saudi: "arabia-saudi",
  arabia_saudita: "arabia-saudi",
  bosnia_y_herzegovina: "bosnia-y-herzegovina",
  nueva_zelanda: "nueva-zelanda",
  cabo_verde: "cabo-verde",
  irlanda_del_norte: "irlanda-del-norte",
  macedonia_del_norte: "macedonia-del-norte",
  emiratos_arabes_unidos: "emiratos-arabes-unidos",
};

const KNOWN_FLAG_FILE_KEYS = new Set([
  "alemania",
  "arabia-saudi",
  "argelia",
  "argentina",
  "australia",
  "austria",
  "belgica",
  "bolivia",
  "bosnia-y-herzegovina",
  "brasil",
  "cabo-verde",
  "canada",
  "colombia",
  "corea",
  "costa-marfil",
  "croacia",
  "curazao",
  "dinamarca",
  "ecuador",
  "egipto",
  "emiratos-arabes-unidos",
  "escocia",
  "eslovaquia",
  "espana",
  "francia",
  "gales",
  "ghana",
  "haiti",
  "holanda",
  "inglaterra",
  "iran",
  "iraq",
  "irlanda",
  "irlanda-del-norte",
  "italia",
  "jamaica",
  "japon",
  "jordania",
  "kosovo",
  "macedonia-del-norte",
  "marruecos",
  "mexico",
  "noruega",
  "nueva-caledonia",
  "nueva-zelanda",
  "panama",
  "paraguay",
  "polonia",
  "portugal",
  "qatar",
  "rd-congo",
  "republica-checa",
  "rumania",
  "senegal",
  "sudafrica",
  "suecia",
  "suiza",
  "surinam",
  "tunez",
  "turquia",
  "ucrania",
  "uruguay",
  "usa",
  "uzbekistan",
]);

export function normalizeCountryKey(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[.'´`,:;!?()[\]{}]/g, "")
    .replace(/[\s\-/\\]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

function fileKeyForCountry(country: string): string | null {
  const normalized = normalizeCountryKey(country);
  const fileKey = FILE_KEY_OVERRIDES[normalized] || normalized.replace(/_/g, "-");
  return KNOWN_FLAG_FILE_KEYS.has(fileKey) ? fileKey : null;
}

export function getFlagPath(country: string): string | null {
  const fileKey = fileKeyForCountry(country);
  return fileKey ? `/flags/${fileKey}.png` : null;
}

export function getFlagEmoji(country: string): string {
  return FLAG_EMOJI_BY_KEY[normalizeCountryKey(country)] || "🏳️";
}

export const KNOWN_FLAG_KEYS = Array.from(KNOWN_FLAG_FILE_KEYS.values());
